name: Ubuntu 24.04 Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  ubuntu_24_04:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y \
            python-is-python3 \
            python3-pip \
            python3-httpx \
            python3-anyio \
            python3-certifi \
            python3-h2 \
            python3-httpcore \
            python3-idna \
            python3-pandas \
            python3-numpy \
            python3-dateutil \
            python3-lxml \
            python3-xmltodict \
            python3-jsonschema \
            python3-pytest \
            python3-pytest-asyncio \
            python3-antlr4 \
            python3-networkx \
            python3-sqlglot \
            python3-respx

      - name: Install pip-only dependencies
        run: |
          pip install --no-dependencies --break-system-packages \
            sdmxschemas \
            parsy \
            msgspec

      - name: Install vtlengine and its dependencies
        run: |
          pip install --no-dependencies --break-system-packages vtlengine==1.3.0

          pip install --break-system-packages --force-reinstall --no-dependencies duckdb

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Build wheel
        run: |
          poetry build -f wheel -o .

      - name: Install built package
        run: |
          pip install "./pysdmx-$(poetry version -s)-py3-none-any.whl" --no-dependencies --break-system-packages

      - name: Run tests
        run: pytest --verbose --tb=short --strict-markers --strict-config
